### ISSUE TITLE
`test/functional/interface_zmq.py` fails when executing the functional test suite

### ISSUE THREAD

**Issue by gto90** [DigiByte-Core/digibyte#96]
### Describe the issue

When executing the functional test suite, `test/functional/interface_zmq.py` fails.  [See here](https://github.com/DigiByte-Core/digibyte/pull/94/files#diff-437d7f6e9f2229879b60aae574a8217f14c643bbf3cfa9225d8011d6d52df00cR139).

### What behavior did you expect?

`test/functional/interface_zmq.py` should not fail when the test runner executes the functional test suite.

### What was the actual behavior (provide screenshots if the issue is GUI-related)?

The `test/functional/interface_zmq.py` functional test fails.  [See here](https://github.com/DigiByte-Core/digibyte/pull/94/files#diff-437d7f6e9f2229879b60aae574a8217f14c643bbf3cfa9225d8011d6d52df00cR139).

### What version of DigiByte Core are you using, where did you get it (website, self-compiled, etc)?

[v8.22](https://github.com/DigiByte-Core/digibyte/tree/feature/8.22.0)

**Comment by JaredTate** [comment]
So its an assertion error:
```
Remaining jobs: [interface_zmq.py]
1/1 - interface_zmq.py failed, Duration: 9 s

stdout:
2022-07-10T18:16:59.875000Z TestFramework (INFO): Initializing test directory /var/folders/w6/gf10tnhx7s36qm0g0wnnnhmw0000gn/T/test_runner_₿_🏃_20220710_121658/interface_zmq_0
2022-07-10T18:17:05.876000Z TestFramework (INFO): Generate 5 blocks (and 5 coinbase txes)
2022-07-10T18:17:05.895000Z TestFramework (INFO): Wait for tx from second node
2022-07-10T18:17:07.427000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/jt/Code/digibyte/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/Users/jt/Code/digibyte/test/functional/interface_zmq.py", line 116, in run_test
    self.test_basic()
  File "/Users/jt/Code/digibyte/test/functional/interface_zmq.py", line 232, in test_basic
    assert_equal(payment_txid, txid.hex())
  File "/Users/jt/Code/digibyte/test/functional/test_framework/util.py", line 51, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(fc10428a8b3922ce1e719395bf4b6ca255c438343f0be28f0267cb574e6aa7d2 == 7ea3dc1b7bd54f7e203818c98f81c3c8b04d313d06272260c1d1bf17e889f67e)
2022-07-10T18:17:07.482000Z TestFramework (INFO): Stopping nodes
2022-07-10T18:17:08.384000Z TestFramework (WARNING): Not cleaning up dir /var/folders/w6/gf10tnhx7s36qm0g0wnnnhmw0000gn/T/test_runner_₿_🏃_20220710_121658/interface_zmq_0
2022-07-10T18:17:08.384000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/w6/gf10tnhx7s36qm0g0wnnnhmw0000gn/T/test_runner_₿_🏃_20220710_121658/interface_zmq_0/test_framework.log
2022-07-10T18:17:08.384000Z TestFramework (ERROR): 
2022-07-10T18:17:08.384000Z TestFramework (ERROR): Hint: Call /Users/jt/Code/digibyte/test/functional/combine_logs.py '/var/folders/w6/gf10tnhx7s36qm0g0wnnnhmw0000gn/T/test_runner_₿_🏃_20220710_121658/interface_zmq_0' to consolidate all logs
2022-07-10T18:17:08.384000Z TestFramework (ERROR): 
2022-07-10T18:17:08.384000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-07-10T18:17:08.385000Z TestFramework (ERROR): https://github.com/DigiByte-Core/digibyte/issues
2022-07-10T18:17:08.385000Z TestFramework (ERROR): 
```

**Comment by SmartArray** [comment]
Unfrotunately, that‘s not all. There is a lot going on in this one and I hope I can find the reason(s) very soon 😀

**Comment by JaredTate** [comment]
Indeed, do you think there is an issue in [test/functional/test_framework/address.py](https://github.com/DigiByte-Core/digibyte/commit/ba128551ea50dfb9ae5359ce0c7ea889e74c9f4f#diff-570c7196d3a92100557837ee9875cdde4d5d81ab7168f164bfd5e8febf63b79b)? How did you calculate these addresses? https://github.com/DigiByte-Core/digibyte/commit/42f481a2581a16588c664a03b0d49f3ada06729d

**Comment by gto90** [comment]
This issue has been resolved by https://github.com/DigiByte-Core/digibyte/pull/106
